
%Add_Include_Paths
%AddIntParams
%AllDefines
%AuxFunc
%AuxHeaders
%AuxType
%BaseType_PLevel_OutParam
%BaseType_PLevel_Return
%BaseType_PLevel_Type
%Block_InsNum
%Block_Param
%Block_Variable
%BuildResult
$C99Mode = 0
%Cache
%CheckedSoLib
%Class_Constructors
%Class_Destructors
%ClassesWithConstructors
%ClassesWithMethods
%ClassInTargetLibrary
%Class_Method
%Class_PureVirtFunc
%Class_SubClasses
%Class_SubClassTypedef
$COMMON_LANGUAGE
%Common_SpecEnv
%Common_SpecType_Exceptions
$CompilerOptions_Headers
%CompilerOptions_Libs
%CompleteSignature
%Constants
%ConstraintNum
%Create_SubClass
$CurrentBlock
%DefaultBinPaths
%DefaultCppHeader
%DefaultCppPaths
%DefaultGccHeader
%DefaultGccPaths
%DefaultIncPaths
%DefaultLibPaths
%DependencyHeaders_All
%DependencyHeaders_All_FullPath
%EnumMembers
%EnumMembName_Id
%ExplicitTypedef
%FuncDescr
%FuncNames
%Func_ShortName_MangledName
%Func_TypeId
($GCC_PATH, $GPP_PATH, $CPP_FILT)
%GenResult
$GLIBC_TESTING
%GlobVarNames
%Header_Dependency
%Header_ErrorRedirect
%Header_Include_Prefix
%Header_Includes
%Header_Interface
$Header_MaxIncludes
%Header_Prefix
%Header_ShouldNotBeUsed
%Header_TopHeader
%IgnoreTmplInst
%IncDir_Prefixes
%Include_Order
%Include_Paths
%Include_Preamble
%Include_Prefixes
%Include_RevOrder
$INC_PATH_AUTODETECT = 1
%InlineTmplCtor
%Interface_LibGroup
%Interface_Library
%Interface_OutParam
%Interface_OutParam_NoUsing
%Interface_Overloads
%Interface_PostCondition
%Interface_PreCondition
%InterfacesList
%InterfaceSpecType
%InterfaceSupplement
%InterfaceSupplement_Lib
%Interface_TestDir
%InterfaceVersion_Library
%InternalInterfaces
%IntrinsicNum
%IntSpecType
%IntSubClass
$IsHeaderListSpecified = 1
%Language
%LibGroups
%LibInfo
%LibraryExitFunc
%LibraryInitFunc
$LibraryMallocFunc
%Library_Prefixes
$LOG_PATH
$MAIN_CPP_DIR
%mangled_name
%mangled_name_gcc
%MangledNames
$MaxTypeId
$MaxTypeId_Start
%Member_Struct
%MethodNames
%NameSpaces
%NeededInterface_Library
%NeededInterfaceVersion_Library
%NestedNameSpaces
$NodeInterface
%OpaqueTypes
%OpenStreams
%OutParam_Interface
%OutParamInterface_Pos
%OutParamInterface_Pos_NoUsing
%OverloadedInterface
$PreprocessedUnit
%ProxyValue = ()
@RecurHeader
@RecurInclude
@RecurInterface
@RecurLib
%RecursiveIncludes
%RecursiveIncludes_Inverse
@RecurSpecType
@RecurSymlink
@RecurTypeId
%RegisteredDirs
%RegisteredHeaders
%RegisteredHeaders_Short
$REPORT_PATH
%RequirementsCatalog
%ResultCounter
%ReturnTypeId_Interface
%RunResult
%SharedObject_Paths
%SharedObject_RecurDeps
%SharedObjects
%SharedObject_UndefinedSymbols
%SigName
%SigNo
%SkipHeaders
%SkipHeaders_Pattern
%SkipInterfaces
%SkipInterfaces_Pattern
%SkipLibs
%SkipLibs_Pattern
%SkipWarnings
%SkipWarnings_Pattern
%SoLib_DefaultPath
%SoLib_IntPrefix
%SpecCode
%SpecEnv
%SpecLibs
%SpecType
%SpecTypeHeaders
$STAT_FIRST_LINE 
$STDCXX_TESTING
%StdCxxTypedef
$ST_ID=0
%StructIDs
%Struct_Mapping
%Struct_Parent
%Struct_SubClasses
%StructUnionPName_Tid
%SubClass_Created
%SubClass_Instance
%SubClass_ObjInstance
%SystemHeaders
%SystemObjects
%SystemObjects_Needed
%SystemPaths
%Target_Headers
%Template2Code_Defines
%TemplateHeader
%TemplateInstance
%TemplateInstance_Func
%TemplateNotInst
$TestedInterface
$TEST_SUITE_PATH
%Tid_TDid
%TName_Tid
%TraceFunc)
%tr_name
%TUnit_NameSpaces
%Typedef_BaseName
%Typedef_Equivalent
%TypedefToAnon
%Typedef_Translations
%TypeDescr
%Type_Typedef
%UsedConstructors
%UsedInterfaces
%UsedProtectedMethods
%UserDefinedOutParam
%UseVarEveryWhere
%ValueCollection
%Wrappers
%Wrappers_SubClasses
