#!/usr/bin/perl
for(<DATA>)
{
	chomp;
	$_=~s/^%//g;
	print "sed 's/\%$_/\%g_$_/g'   /usr/bin/api-sanity-checker -i \n";
	print "sed 's/\$$_/\$g_$_/g'   /usr/bin/api-sanity-checker -i \n";
}

#下面可以能出现情况,  好像没有效果. 
#通过lmyunit 测试下来 /root/lmyunit/lmyunit/one_step_lmyunit_ASC.sh , 还是可以生成的 。
#下面的 case , 不会发生 bug
sub bug_notice()
{
print <<EOF
%mangled_name
%mangled_name_gcc
EOF
;

}
__DATA__

%AddIntParams
%Add_Include_Paths
%AllDefines
%AuxFunc
%AuxHeaders
%AuxType
%BaseType_PLevel_OutParam
%BaseType_PLevel_Return
%BaseType_PLevel_Type
%Block_InsNum
%Block_Param
%Block_Variable
%BuildResult
%Cache
%CheckedSoLib
%ClassInTargetLibrary
%Class_Constructors
%Class_Destructors
%Class_Method
%Class_PureVirtFunc
%Class_SubClassTypedef
%Class_SubClasses
%ClassesWithConstructors
%ClassesWithMethods
%Common_SpecEnv
%Common_SpecType_Exceptions
%CompilerOptions_Libs
%CompleteSignature
%Constants
%ConstraintNum
%Create_SubClass
%DefaultBinPaths
%DefaultCppHeader
%DefaultCppPaths
%DefaultGccHeader
%DefaultGccPaths
%DefaultIncPaths
%DefaultLibPaths
%DependencyHeaders_All
%DependencyHeaders_All_FullPath
%EnumMembName_Id
%EnumMembers
%ExplicitTypedef
%FuncDescr
%FuncNames
%Func_ShortName_MangledName
%Func_TypeId
%GenResult
%GlobVarNames
%Header_Dependency
%Header_ErrorRedirect
%Header_Include_Prefix
%Header_Includes
%Header_Interface
%Header_Prefix
%Header_ShouldNotBeUsed
%Header_TopHeader
%IgnoreTmplInst
%IncDir_Prefixes
%Include_Order
%Include_Paths
%Include_Preamble
%Include_Prefixes
%Include_RevOrder
%InlineTmplCtor
%IntSpecType
%IntSubClass
%InterfaceSpecType
%InterfaceSupplement
%InterfaceSupplement_Lib
%InterfaceVersion_Library
%Interface_LibGroup
%Interface_Library
%Interface_OutParam
%Interface_OutParam_NoUsing
%Interface_Overloads
%Interface_PostCondition
%Interface_PreCondition
%Interface_TestDir
%InterfacesList
%InternalInterfaces
%IntrinsicNum
%Language
%LibGroups
%LibInfo
%LibraryExitFunc
%LibraryInitFunc
%Library_Prefixes
%MangledNames
%Member_Struct
%MethodNames
%NameSpaces
%NeededInterfaceVersion_Library
%NeededInterface_Library
%NestedNameSpaces
%OpaqueTypes
%OpenStreams
%OutParamInterface_Pos
%OutParamInterface_Pos_NoUsing
%OutParam_Interface
%OverloadedInterface
%ProxyValue
%RecursiveIncludes
%RecursiveIncludes_Inverse
%RegisteredDirs
%RegisteredHeaders
%RegisteredHeaders_Short
%RequirementsCatalog
%ResultCounter
%ReturnTypeId_Interface
%RunResult
%SharedObject_Paths
%SharedObject_RecurDeps
%SharedObject_UndefinedSymbols
%SharedObjects
%SigName
%SigNo
%SkipHeaders
%SkipHeaders_Pattern
%SkipInterfaces
%SkipInterfaces_Pattern
%SkipLibs
%SkipLibs_Pattern
%SkipWarnings
%SkipWarnings_Pattern
%SoLib_DefaultPath
%SoLib_IntPrefix
%SpecCode
%SpecEnv
%SpecLibs
%SpecType
%SpecTypeHeaders
%StdCxxTypedef
%StructIDs
%StructUnionPName_Tid
%Struct_Mapping
%Struct_Parent
%Struct_SubClasses
%SubClass_Created
%SubClass_Instance
%SubClass_ObjInstance
%SystemHeaders
%SystemObjects
%SystemObjects_Needed
%SystemPaths
%TName_Tid
%TUnit_NameSpaces
%Target_Headers
%Template2Code_Defines
%TemplateHeader
%TemplateInstance
%TemplateInstance_Func
%TemplateNotInst
%Tid_TDid
%TraceFunc
%TypeDescr
%Type_Typedef
%TypedefToAnon
%Typedef_BaseName
%Typedef_Equivalent
%Typedef_Translations
%UseVarEveryWhere
%UsedConstructors
%UsedInterfaces
%UsedProtectedMethods
%UserDefinedOutParam
%ValueCollection
%Wrappers
%Wrappers_SubClasses
%mangled_name
%mangled_name_gcc
%tr_name
