#!/usr/bin/perl
foreach (<DATA>)
{
	print $_;
}
__DATA__
cal::month
Math::Random
File::Copy::
PPT::test
Log::Log4perl::Appender::File
cal::year,
Net::MAC::Vendor::parse_oui
IPV4Address::classifyNetwork
Math::BigInt
POSIX::setsid
File::Path
cal::jd
LCS::diff
@Any_DBM_File::ISA
List::MoreUtils
CPAN::DEBUG
cal::month++
cal::month
IO::Tac
POSIX::isprint
String::ShellQuote
Time::Local::timelocal
Text::ParseWords
String::Random
cp::EXIT_STATUS++
Sys::Hostname::hostname
URI::Escape
IO::Handle
File::
File::Find::topdir
IPV4Address::new
IPV4Address::scan
FastGlob::matched
HTML::Entities
Fcntl::O_CREAT
I18N::Langinfo
IPV4Address::fillBits
File::Find::prune
Patch::Normal
FastGlob::rootpat
File::Copy::move
Search::Dict
Net::MSN::VERSION
%mailbox::fields,
cp::PATH||
::EXPORT_OK
::throw
IPV4Address::and
IPV4Address::hex
IPV4Address::countBits
List::Util
DB_File::Lock,BTREE
HTML::TreeBuilder::Debug
IPV4Address::bitVector
main::VERSION,
cp::CWD|
MIME::Body::File
main::fd_stdin,
IPV4Address::not
POSIX::ECHO
File::Copy::copy
Digest::
FastGlob::parentdir
Net::MAC::Vendor::lookup
MyME::Parser
POSIX::ttyname
cal::num_args
%Algorithm::Diff::EXPORT_OK
File::Sort
Log::Log4perl::Layout::PatternLayout
MLDBM::Serializer
WWW::Search::RpmFind,
Pod::Usage
main::box
main::parse_msg_list
@FastGlob::errors
Example::
HTML::Element
File::Basename::dirname
SUPER::apply
BerkeleyDB::Error
Template::
FindBin::Bin
Date::Pcalc
HTML::TableContentParser,
%message::fields,
DB_File::Lock
Filesys::DiskSpace
WWW::Search::escape_query
MIME::Body::Scalar
Pod::Usage::pod2usage
HTML::TokeParser
Data::Dumper  
Algorithm::Diff::VERSION
main::VERSION_MESSAGE
CPAN::Module::force
Patch::Ed
MacPerl::Version
Getopt::Long::GetOptions
cal::year
cal::jd,
::  
IPV4Address::byte
::ISA
main::HELP_MESSAGE
FastGlob::dirsep
File::Basename::basename
Patch::
%mailer::fields,
FastGlob::curdir
HTML::DOM,
Text::Tabs,
SUPER::rummage
%editor::fields,
main::COLS
IPV4Address::copy
File::Find|File::Find
main::DATA  
Patch::Unified
Apache::Session
WWW::Freshmeat
Math::
FastGlob::hidedotfiles
Algorithm::LCS::diff
IPV4Address::overlayBits
ANSI::Color
Storable::thaw
MacPerl::Pick
IPV4Address::decimal
Math::BigFloat::panic
File::Sort,
WWW::Search::RpmFind::VERSION,  
IO::Socket
File::Temp
HTML::Parse
File::Find::dont_use_nlink
Patch::Context
FreezeThaw::thaw
Net::MAC::Vendor
Log::singleton
CLASS::CONSTANT
String::Similarity
Sys::Hostname
FindBin::Script
Data::ShowTable
SymbolicMode::mod
cp::CASE_SENSITIVE
HTML::TreeBuilder::DEBUG
File::stat
Carp::croak
main::noecho
LWP::Simple
Stat::lsMode
%mailer::fields
File::Find::dir
MLDBM::UseDB
File::Copy
Getopt::Std
main::fd_stdin
Lingua::Stem
HTML::FormatText
Date::Parse
File::Copy::Recursive
%message::fields
Log::Log4perl
cp::EXIT_STATUS
cal::yr
Digest::SHA1
POSIX::Termios
MIME::Lite
Net::FTP
Net::Ping
cp::BINMODE
siteinfo::basedir
DB_File::DB_HASH
HTTP::Request
main::Timeout
main::opt_i
Spreadsheet::ParseExcel
Compress::Zlib
Getopt::Long::Configure
cp::PATH
main::DATA
Mail::Mailer
GD::Image
MIME::Parser
%mailbox::fields
Term::ANSIColor::color
Getopt::Long
%editor::fields
Dev::Null
cp::CWD
SET::toplines
main::echo
HTML::TableExtract
DB_File::DB_BTREE
main::oterm
HTML::LinkExtractor
DB_File::DB_RECNO
siteinfo::img_prevue_name
main::opt_f
WWW::Search
cp::USES_DRIVE_LETTER
Algorithm::Diff
main::opt_v
Image::Size
Term::ANSIColor
HTML::DOM
Text::CSV_XS
IO::File
Mail::Webmail::Yahoo
Net::SMTP
File::Basename
WWW::Search::RpmFind
Getopt::Long::config
Time::Local
HTML::TreeBuilder::XPath
POSIX::strftime
Net::MSN
Term::Cap
HTML::TableContentParser
URI::URL
Lingua::ZH::Numbers::Currency
Data::Dumper
main::debug
main::opt_p
Math::BigFloat
File::Find
::
IO::Select
File::Find::find
File::Spec
HTML::TreeBuilder
CPAN::Shell
LWP::UserAgent
main::term
File::Find::name
cp::TARGET
IO::Socket::INET

