#!/usr/bin/perl
foreach (<DATA>)
{
	print $_;
}
__DATA__
# Kickstart file automatically generated by anaconda.

install
#cdrom
nfs --server=192.168.3.47 --dir=/mnt/sdb1
lang en_US.UTF-8
keyboard us
network --device eth0 --bootproto static --ip 192.168.3.225 --netmask 255.255.255.0 --gateway 192.168.3.254 --nameserver 202.96.209.5,202.96.209.133 --hostname localhost
rootpw --iscrypted /0JK5q6eb.U2dLvHjdK1
firewall --disabled
authconfig --enableshadow --enablemd5
selinux --disabled
timezone Asia/Shanghai
bootloader --location=mbr 
clearpart --all 
autopart
zerombr yes
reboot

%packages
@legacy-network-server
@smb-server
@web-server

%post
chkconfig sendmail off
[ -x /system/install ] && cd /system && ./install


