#!/usr/bin/perl
foreach (<DATA>)
{
	print $_;
}
__DATA__
"Meta-Commands"
########################################################################
".abandon (Abandon Process)"
".allow_exec_cmds (Allow Execution Commands)"
".allow_image_mapping (Allow Image Mapping)"
".apply_dbp (Apply Data Breakpoint to Context)"
".asm (Change Disassembly Options)"
".attach (Attach to Process)"
".beep (Speaker Beep)"
".bpcmds (Display Breakpoint Commands)"
".bpsync (Synchronize Threads at Breakpoint)"
".breakin (Break to the Kernel Debugger)"
".bugcheck (Display Bug Check Data)"
".cache (Set Cache Size)"
".call (Call Function)"
".chain (List Debugger Extensions)"
".childdbg (Debug Child Processes)"
".clients (List Debugging Clients)"
".closehandle (Close Handle)"
".cls (Clear Screen)"
".context (Set User-Mode Address Context)"
".copysym (Copy Symbol Files)"
".cordll (Control CLR Debugging)"
".crash (Force System Crash)"
".create (Create Process)"
".createdir (Set Created Process Directory)"
".cxr (Display Context Record)"
".dbgdbg (Debug Current Debugger)"
".detach (Detach from Process)"
".dump (Create Dump File)"
".dumpcab (Create Dump File CAB)"
".dvalloc (Allocate Memory)"
".dvfree (Free Memory)"
".echo (Echo Comment)"
".echocpunum (Show CPU Number)"
".echotime (Show Current Time)"
".echotimestamps (Show Time Stamps)"
".ecxr (Display Exception Context Record)"
".effmach (Effective Machine)"
".enable_long_status (Enable Long Integer Display)"
".enable_unicode (Enable Unicode Display)"
".endpsrv (End Process Server)"
".endsrv (End Debugging Server)"
".enumtag (Enumerate Secondary Callback Data)"
".event_code (Display Event Code)"
".eventlog (Display Recent Events)"
".exepath (Set Executable Path)"
".expr (Choose Expression Evaluator)"
".exptr (Display Exception Pointers)"
".exr (Display Exception Record)"
".extmatch (Display All Matching Extensions)"
".extpath (Set Extension Path)"
".f+, .f- (Shift Local Context)"
".fiber (Set Fiber Context)"
".fiximports (Fix Target Module Imports)"
".flash_on_break (Flash on Break)"
".fnent (Display Function Data)"
".fnret (Display Function Return Value)"
".force_radix_output (Use Radix for Integers)"
".force_tb (Forcibly Allow Branch Tracing)"
".formats (Show Number Formats)"
".fpo (Control FPO Overrides)"
".frame (Set Local Context)"
".help (Meta-Command Help)"
".hh (Open HTML Help File)"
".holdmem (Hold and Compare Memory)"
".idle_cmd (Set Idle Command)"
".ignore_missing_pages (Suppress Missing Page Errors)"
".imgscan (Find Image Headers)"
".kdfiles (Set Driver Replacement Map)"
".kframes (Set Stack Length)"
".kill (Kill Process)"
".lastevent (Display Last Event)"
".lines (Toggle Source Line Support)"
".load, .loadby (Load Extension DLL)"
".locale (Set Locale)"
".logappend (Append Log File)"
".logclose (Close Log File)"
".logfile (Display Log File Status)"
".logopen (Open Log File)"
".netuse (Control Network Connections)"
".noshell (Prohibit Shell Commands)"
".noversion (Disable Version Checking)"
".ocommand (Expect Commands from Target)"
".ofilter (Filter Target Output)"
".open (Open Source File)"
".opendump (Open Dump File)"
".outmask (Control Output Mask)"
".pagein (Page In Memory)"
".pcmd (Set Prompt Command)"
".pop (Restore Debugger State)"
".process (Set Process Context)"
".prompt_allow (Control Prompt Display)"
".push (Save Debugger State)"
".quit_lock (Prevent Accidental Quit)"
".readmem (Read Memory from File)"
".reboot (Reboot Target Computer)"
".record_branches (Enable Branch Recording)"
".reload (Reload Module)"
".remote (Create Remote.exe Server)"
".remote_exit (Exit Debugging Client)"
".restart (Restart Target Application)"
".restart (Restart Kernel Connection)"
".scroll_prefs (Control Source Scrolling Preferences)"
".secure (Activate Secure Mode)"
".send_file (Send File)"
".server (Create Debugging Server)"
".servers (List Debugging Servers)"
".setdll (Set Default Extension DLL)"
".shell (Command Shell)"
".sleep (Pause Debugger)"
".sound_notify (Use Notification Sound)"
".srcfix, .lsrcfix (Use Source Server)"
".srcnoisy (Noisy Source Loading)"
".srcpath, .lsrcpath (Set Source Path)"
".step_filter (Set Step Filter)"
".suspend_ui (Suspend WinDbg Interface)"
".symfix (Set Symbol Store Path)"
".symopt (Set Symbol Options)"
".sympath (Set Symbol Path)"
".thread (Set Register Context)"
".time (Display System Time)"
".tlist (List Process IDs)"
".trap (Display Trap Frame)"
".tss (Display Task State Segment)"
".ttime (Display Thread Times)"
".typeopt (Set Type Options)"
".unload (Unload Extension DLL)"
".unloadall (Unload All Extension DLLs)"
".wake (Wake Debugger)"
".write_cmd_hist (Write Command History)"
".writemem (Write Memory to File)"
".wtitle (Set Window Title)"


