#!/usr/bin/perl
if( ! -f "install-module.pl")
{
	die("ERROR: current dir is not webmin  dir , should run it  in  webmin dir \n");
}


for (glob("./*/module.info"))
{
	local %minfo;
	my $name=$_;
	&read_file($_, \%minfo);

	$name=~s/module.info//g;
	$name=~s/\///g;
	$name=~s/\.//g;

	print "#========================================================================== \n";
	print "Name=".$name."\n";
	my $desc= $minfo{'desc'};
	$desc=~s/\//_/g;
	my $longdesc= $minfo{'longdesc'}."\n";
	#print $_."\n";
	save_to_file($name, $desc, $longdesc);
	
}

sub save_to_file($$$)
{
	(my $path, my $desc, my $long_desc)=@_;
	my $output="/tmp/webmin_".$path."_".$desc.".txt";
	open(OUTPUT, "> $output") or die("Open webmin  $output error \n");
	my $cur_time=get_now();
	print OUTPUT  "#$cur_time add by greshem \n";
	print OUTPUT  "#generated by  develop_perl/get_desc_webmin_keyword_to_txt.pl \n";

	print OUTPUT  "Path: webmin/$path \n";
	print OUTPUT  "desc: $desc \n";
	print OUTPUT  "longdesc: $long_desc  \n";
	close(OUTPUT);
}

# read_file(file, array)
# Fill an associative array with name=value pairs from a file
# from  webmin thridpart.pl 
sub read_file
{
local($arr);
$arr = $_[1];
open(ARFILE, $_[0]) || return 0;
while(<ARFILE>) {
        chop;
        if (!/^#/ && /^([^=]+)=(.*)$/) { $$arr{$1} = $2; }
        }
close(ARFILE);
return 1;
}
 

sub get_now()
{
	use POSIX 'strftime';
	$cur_time=POSIX::strftime('%Y-%m-%d-%T_%A',localtime(time()));
	print "nowTime -> ", $cur_time,"\n";
	return $cur_time;
}

